# yaml-language-server: $schema=https://raw.githubusercontent.com/greatliontech/semrel/refs/heads/main/config.schema.json
patchTypes:
  - fix
minorTypes:
  - feat
development: true
createTag: true
pushTag: true
