name: goreleaser

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: semrel
        uses: greatliontech/semrel-action@main

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Create Tag
        run: |
          if [ "${{ steps.semrel.outputs.next-version }}" == "${{ steps.semrel.outputs.current-version }}" ]; then
            echo "No new version to release"
            exit 0
          fi
          git tag ${{ steps.semrel.outputs.next-version }}
          git push origin ${{ steps.semrel.outputs.next-version }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
          AUR_SSH_KEY: ${{ secrets.AUR_SSH_KEY }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          GORELEASER_CURRENT_TAG: ${{ steps.semrel.outputs.next-version }}
          GORELEASER_PREVIOUS_TAG: ${{ steps.semrel.outputs.current-version }}
