on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  semrel:
    runs-on: ubuntu-latest
    name: Semantic Release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: semrel
        uses: thegrumpylion/semrel-action@main
      - run: |
          echo next-ver = $NEXT_VERSION
          echo cur-ver = $CUR_VERSION
        shell: bash
        env:
          NEXT_VERSION: ${{ steps.semrel.outputs.next-version }}
          CUR_VERSION: ${{ steps.semrel.outputs.current-version }}
